In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv('students_data.csv')

In [3]:
# regression
#dataset = pd.DataFrame({"weight": dataset["weight"]/100, "num_of_prev_attempts": dataset["num_of_prev_attempts"]/6, "studied_credits" : dataset["studied_credits"]/665, "assessment_type" : dataset["assessment_type"], "date": dataset["date"]/261.0, "activity_type": dataset["activity_type"], "gender": dataset["gender"], "region": dataset["region"], "highest_education": dataset["highest_education"],"imd_band":dataset["imd_band"], "age_band":dataset["age_band"], "studied_credits": dataset["studied_credits"]/655, "disability":dataset["disability"], "date_submitted": dataset["date_submitted"]/261, "is_banked":dataset["is_banked"], "sum_click":dataset["sum_click"]/6977,  "score": dataset["score"]/100  })
#dataset#.head(10) #one hot --> assessment_type, activity_type, gender, region, highest_education,imd_band,age_band, is_banked

In [4]:
# categorical
#dataset = pd.DataFrame({"weight": dataset["weight"]/100, "num_of_prev_attempts": dataset["num_of_prev_attempts"]/6, "studied_credits" : dataset["studied_credits"]/665, "assessment_type" : dataset["assessment_type"], "date": dataset["date"]/261.0, "activity_type": dataset["activity_type"], "gender": dataset["gender"], "region": dataset["region"], "highest_education": dataset["highest_education"],"imd_band":dataset["imd_band"], "age_band":dataset["age_band"], "studied_credits": dataset["studied_credits"]/655, "disability":dataset["disability"], "date_submitted": dataset["date_submitted"]/261, "is_banked":dataset["is_banked"], "sum_click":dataset["sum_click"]/6977,  "ECTS": dataset["ECTS"]  })
dataset = pd.DataFrame({"weight": dataset["weight"]/100, "num_of_prev_attempts": dataset["num_of_prev_attempts"]/6, "studied_credits" : dataset["studied_credits"]/665, "assessment_type" : dataset["assessment_type"], "date": dataset["date"]/261.0, "activity_type": dataset["activity_type"], "gender": dataset["gender"], "region": dataset["region"], "highest_education": dataset["highest_education"],"imd_band":dataset["imd_band"], "age_band":dataset["age_band"], "studied_credits": dataset["studied_credits"]/655, "disability":dataset["disability"], "date_submitted": dataset["date_submitted"]/261, "is_banked":dataset["is_banked"], "sum_click":dataset["sum_click"]/6977,  "final_result": dataset["final_result"], "score": dataset["score"]  })
dataset#.head(10) #one hot --> assessment_type, activity_type, gender, region, highest_education,imd_band,age_band, is_banked, ECTS

weight  num_of_prev_attempts  studied_credits assessment_type  \
0          0.2                   0.0         0.366412             TMA   
1          0.2                   0.0         0.091603             TMA   
2          0.2                   0.0         0.091603             TMA   
3          0.2                   0.0         0.091603             TMA   
4          0.2                   0.0         0.091603             TMA   
...        ...                   ...              ...             ...   
613957     0.0                   0.0         0.045802             TMA   
613958     0.0                   0.0         0.045802             TMA   
613959     0.0                   0.0         0.045802             TMA   
613960     0.0                   0.0         0.045802             TMA   
613961     0.0                   0.0         0.045802             TMA   

            date activity_type gender                region  \
0       0.206897      homepage      M   East Anglian Region   
1       0.206897      homepage      F     South East Region   
2       0.206897       forumng      F     South East Region   
3       0.206897       forumng      F     South East Region   
4       0.448276      homepage      F     South East Region   
...          ...           ...    ...                   ...   
613957  0.448276     oucontent      F  North Western Region   
613958  0.448276     oucontent      F  North Western Region   
613959  0.448276          quiz      F  North Western Region   
613960  0.448276      homepage      F  North Western Region   
613961  0.448276       subpage      F  North Western Region   

            highest_education imd_band age_band disability  date_submitted  \
0            HE Qualification  90-100%     55<=          N        0.203065   
1       A Level or Equivalent   50-60%    35-55          N        0.195402   
2       A Level or Equivalent   50-60%    35-55          N        0.195402   
3       A Level or Equivalent   50-60%    35-55          N        0.195402   
4       A Level or Equivalent   50-60%    35-55          N        0.440613   
...                       ...      ...      ...        ...             ...   
613957     Lower Than A Level   20-30%    35-55          N        0.448276   
613958     Lower Than A Level   20-30%    35-55          N        0.448276   
613959     Lower Than A Level   20-30%    35-55          N        0.448276   
613960     Lower Than A Level   20-30%    35-55          N        0.448276   
613961     Lower Than A Level   20-30%    35-55          N        0.448276   

        is_banked  sum_click final_result  score  
0               0   0.000143         Pass   85.0  
1               0   0.000143         Pass   71.0  
2               0   0.000287         Pass   71.0  
3               0   0.000287         Pass   71.0  
4               0   0.000143         Pass   74.0  
...           ...        ...          ...    ...  
613957          0   0.000143         Pass   60.0  
613958          0   0.000143         Pass   60.0  
613959          0   0.000143         Pass   60.0  
613960          0   0.000143         Pass   60.0  
613961          0   0.000143         Pass   60.0  

[613962 rows x 17 columns]

In [5]:
# categorical
#dataset = pd.DataFrame({"weight": dataset["weight"]/100, "num_of_prev_attempts": dataset["num_of_prev_attempts"]/6, "studied_credits" : dataset["studied_credits"]/665, "assessment_type" : dataset["assessment_type"], "date": dataset["date"]/261.0, "activity_type": dataset["activity_type"], "gender": dataset["gender"], "region": dataset["region"], "highest_education": dataset["highest_education"],"imd_band":dataset["imd_band"], "age_band":dataset["age_band"], "studied_credits": dataset["studied_credits"]/655, "disability":dataset["disability"], "date_submitted": dataset["date_submitted"]/261, "is_banked":dataset["is_banked"], "sum_click":dataset["sum_click"]/6977,  "final_result": dataset["final_result"]  })
#dataset#.head(10) #one hot --> assessment_type, activity_type, gender, region, highest_education,imd_band,age_band, is_banked, final_result

In [6]:
dataset[dataset.eq('Withdrawn').any(1)]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


weight  num_of_prev_attempts  studied_credits assessment_type  \
1602      0.20                   0.0         0.091603             TMA   
1603      0.20                   0.0         0.091603             TMA   
1604      0.20                   0.0         0.091603             TMA   
1605      0.20                   0.0         0.091603             TMA   
2892      0.10                   0.0         0.183206             TMA   
...        ...                   ...              ...             ...   
576518    0.25                   0.0         0.183206             TMA   
576519    0.25                   0.0         0.183206             TMA   
576520    0.25                   0.0         0.183206             TMA   
576521    0.25                   0.0         0.183206             TMA   
576522    0.25                   0.0         0.183206             TMA   

            date activity_type gender         region      highest_education  \
1602    0.448276      homepage      F  London Region  A Level or Equivalent   
1603    0.448276     oucontent      F  London Region  A Level or Equivalent   
1604    0.448276     oucontent      F  London Region  A Level or Equivalent   
1605    0.448276     oucontent      F  London Region  A Level or Equivalent   
2892    0.072797      homepage      F   South Region     Lower Than A Level   
...          ...           ...    ...            ...                    ...   
576518  0.333333       subpage      M   South Region     Lower Than A Level   
576519  0.333333     oucontent      M   South Region     Lower Than A Level   
576520  0.333333      resource      M   South Region     Lower Than A Level   
576521  0.333333      homepage      M   South Region     Lower Than A Level   
576522  0.333333       subpage      M   South Region     Lower Than A Level   

       imd_band age_band disability  date_submitted  is_banked  sum_click  \
1602     80-90%    35-55          N        0.486590          0   0.000573   
1603     80-90%    35-55          N        0.486590          0   0.000430   
1604     80-90%    35-55          N        0.486590          0   0.000860   
1605     80-90%    35-55          N        0.486590          0   0.000717   
2892     50-60%     55<=          N        0.084291          0   0.000143   
...         ...      ...        ...             ...        ...        ...   
576518   20-30%     0-35          N        0.375479          0   0.000143   
576519   20-30%     0-35          N        0.375479          0   0.000430   
576520   20-30%     0-35          N        0.375479          0   0.000143   
576521   20-30%     0-35          N        0.375479          0   0.000287   
576522   20-30%     0-35          N        0.375479          0   0.000143   

       final_result  score  
1602      Withdrawn    NaN  
1603      Withdrawn    NaN  
1604      Withdrawn    NaN  
1605      Withdrawn    NaN  
2892      Withdrawn    NaN  
...             ...    ...  
576518    Withdrawn    NaN  
576519    Withdrawn    NaN  
576520    Withdrawn    NaN  
576521    Withdrawn    NaN  
576522    Withdrawn    NaN  

[141 rows x 17 columns]

In [7]:
dataset= dataset.dropna()

In [8]:
dataset[dataset.eq('Withdrawn').any(1)]

Empty DataFrame
Columns: [weight, num_of_prev_attempts, studied_credits, assessment_type, date, activity_type, gender, region, highest_education, imd_band, age_band, disability, date_submitted, is_banked, sum_click, final_result, score]
Index: []

In [9]:
dataset.drop(['score'],axis =1, inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [10]:
# from sklearn.preprocessing import OneHotEncoder
# ohe = OneHotEncoder()
# X = ohe.fit_transform(X).toarray()

In [11]:
#dataset = pd.get_dummies(dataset, prefix=['assessment_type', 'activity_type', 'gender', 'region', 'highest_education','imd_band','age_band', 'is_banked']) # regresion with scores
#dataset = pd.get_dummies(dataset, prefix=['assessment_type', 'activity_type', 'gender', 'region', 'highest_education','imd_band','age_band', 'is_banked', 'ECTS']) # categorical with ECTS
dataset = pd.get_dummies(dataset, prefix=['assessment_type', 'activity_type', 'gender', 'region', 'highest_education','imd_band','age_band', 'is_banked', 'final_result']) # categorical with final_result

In [12]:
#dataset.drop(['assessment_type', 'activity_type', 'gender', 'region', 'highest_education','imd_band','age_band'],axis=1, inplace=True)

In [13]:
dataset

weight  num_of_prev_attempts  studied_credits      date  \
0          0.2                   0.0         0.366412  0.206897   
1          0.2                   0.0         0.091603  0.206897   
2          0.2                   0.0         0.091603  0.206897   
3          0.2                   0.0         0.091603  0.206897   
4          0.2                   0.0         0.091603  0.448276   
...        ...                   ...              ...       ...   
613957     0.0                   0.0         0.045802  0.448276   
613958     0.0                   0.0         0.045802  0.448276   
613959     0.0                   0.0         0.045802  0.448276   
613960     0.0                   0.0         0.045802  0.448276   
613961     0.0                   0.0         0.045802  0.448276   

        date_submitted  is_banked  sum_click  assessment_type_CMA  \
0             0.203065          0   0.000143                    0   
1             0.195402          0   0.000143                    0   
2             0.195402          0   0.000287                    0   
3             0.195402          0   0.000287                    0   
4             0.440613          0   0.000143                    0   
...                ...        ...        ...                  ...   
613957        0.448276          0   0.000143                    0   
613958        0.448276          0   0.000143                    0   
613959        0.448276          0   0.000143                    0   
613960        0.448276          0   0.000143                    0   
613961        0.448276          0   0.000143                    0   

        assessment_type_Exam  assessment_type_TMA  ...  imd_band_70-80%  \
0                          0                    1  ...                0   
1                          0                    1  ...                0   
2                          0                    1  ...                0   
3                          0                    1  ...                0   
4                          0                    1  ...                0   
...                      ...                  ...  ...              ...   
613957                     0                    1  ...                0   
613958                     0                    1  ...                0   
613959                     0                    1  ...                0   
613960                     0                    1  ...                0   
613961                     0                    1  ...                0   

        imd_band_80-90%  imd_band_90-100%  age_band_0-35  age_band_35-55  \
0                     0                 1              0               0   
1                     0                 0              0               1   
2                     0                 0              0               1   
3                     0                 0              0               1   
4                     0                 0              0               1   
...                 ...               ...            ...             ...   
613957                0                 0              0               1   
613958                0                 0              0               1   
613959                0                 0              0               1   
613960                0                 0              0               1   
613961                0                 0              0               1   

        age_band_55<=  is_banked_N  is_banked_Y  final_result_Fail  \
0                   1            1            0                  0   
1                   0            1            0                  0   
2                   0            1            0                  0   
3                   0            1            0                  0   
4                   0            1            0                  0   
...               ...          ...          ...                ...   
613957              0            1            0                  0   


In [14]:
len(dataset)

576754

In [15]:
X = dataset.iloc[:,:64].values
y = dataset.iloc[:,64:66].values

In [16]:
y

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [0, 1],
       [0, 1],
       [0, 1]], dtype=uint8)

In [17]:
X

array([[0.2       , 0.        , 0.36641221, ..., 1.        , 1.        ,
        0.        ],
       [0.2       , 0.        , 0.09160305, ..., 0.        , 1.        ,
        0.        ],
       [0.2       , 0.        , 0.09160305, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.04580153, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.04580153, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.04580153, ..., 0.        , 1.        ,
        0.        ]])

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25)

In [19]:
y_train

array([[0, 1],
       [0, 1],
       [1, 0],
       ...,
       [0, 1],
       [0, 1],
       [0, 1]], dtype=uint8)

In [20]:
#########################################################################

In [21]:
########################           Building Neural Network

In [22]:
#########################################################################

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [24]:
model = Sequential()
model.add(Dense(42, input_dim=64, activation='relu'))
model.add(Dense(24, activation='relu'))
model.add(Dense(2, activation='linear'))

In [25]:
#model.compile(loss='mean_squared_error', optimizer='sgd', metrics=['accuracy']) #regresion
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) #categorical

In [26]:
history = model.fit(X_train, y_train, epochs=10, batch_size=64)

Train on 432565 samples
Epoch 1/10
432565/432565 [==============================] - 16s 37us/sample - loss: 0.3376 - accuracy: 0.8991
Epoch 2/10
432565/432565 [==============================] - 15s 34us/sample - loss: 0.2941 - accuracy: 0.9025
Epoch 3/10
432565/432565 [==============================] - 16s 36us/sample - loss: 0.2872 - accuracy: 0.9030
Epoch 4/10
432565/432565 [==============================] - 17s 39us/sample - loss: 0.2814 - accuracy: 0.9033
Epoch 5/10
432565/432565 [==============================] - 17s 39us/sample - loss: 0.2799 - accuracy: 0.9037
Epoch 6/10
432565/432565 [==============================] - 18s 41us/sample - loss: 0.2787 - accuracy: 0.9036
Epoch 7/10
432565/432565 [==============================] - 17s 39us/sample - loss: 0.2745 - accuracy: 0.9039
Epoch 8/10
432565/432565 [==============================] - 18s 41us/sample - loss: 0.3297 - accuracy: 0.8510
Epoch 9/10
432565/432565 [==============================] - 18s 41us/sample - loss: 0.3029 - acc

In [27]:
y_pred = model.predict(X_test)

In [28]:
y_pred

array([[1.780586  , 9.992189  ],
       [0.557401  , 6.7618604 ],
       [0.73540026, 7.892099  ],
       ...,
       [0.49286336, 6.145511  ],
       [0.27962622, 6.7362256 ],
       [1.6139835 , 6.987026  ]], dtype=float32)