In [1]:
import tensorflow as tf

# 0D Tensor
d0 = tf.ones((1,))

In [2]:
# 1D Tensor
d1 = tf.ones((2,))

In [3]:
# 2D Tensor
d2 = tf.ones((2,2))

In [4]:
# 3D Tensor
d3 = tf.ones((2,3,2))

In [5]:
# Print the 3D tensor
print(d3.numpy())

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [6]:
from tensorflow import constant
#Define a 2x3 constant
a = constant(3, shape = [2,3])

In [7]:
b = constant([1,2,3,4], shape=[2,2])

In [8]:
print(b.numpy())

[[1 2]
 [3 4]]


In [9]:
a0 = tf.Variable([1,2,3,4,5,6], dtype = tf.float32)
a1 = tf.Variable([1,2,3,4,5,6], dtype = tf.int16)

In [10]:
b = tf.constant(2, tf.float32)

In [11]:
c0 = tf.multiply(a0, b)
c1 = a0 + b
c1

<tf.Tensor: id=37, shape=(6,), dtype=float32, numpy=array([3., 4., 5., 6., 7., 8.], dtype=float32)>

In [12]:
import numpy

In [13]:

# Define the 1-dimensional variable A1
A1 = tf.Variable([1, 2, 3, 4])

# Print the variable A1
print(A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print(B1)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>
[1 2 3 4]


In [14]:
from tensorflow import constant, add

In [15]:
A0 = constant([1])
B0 = constant([2])

In [16]:
A1 = constant([1, 2]) 
B1 = constant([3, 4]) 

In [18]:
A2 = constant([[1, 2], [3, 4]])
B2 = constant([[5, 6], [7, 8]])

In [19]:
C0 = add(A0, B0)
C1 = add(A1, B1) 
C2 = add(A2, B2) 

In [20]:
from tensorflow import ones, matmul, multiply 
# Define tensors 
A0 = ones(1) 
A31 = ones([3, 1]) 
A34 = ones([3, 4]) 
A43 = ones([4, 3])

In [21]:
multiply(A31, A31)

<tf.Tensor: id=70, shape=(3, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [22]:
from tensorflow import ones, reduce_sum
A = ones([2, 3, 4]) 
B = reduce_sum(A) 
 
# Sum over dimensions 0, 1, and 2
B0 = reduce_sum(A, 0) 
B1 = reduce_sum(A, 1) 
B2 = reduce_sum(A, 2)

In [23]:
#Advanced operations

In [24]:
import tensorflow as tf 
x = tf.Variable(-1.0) 

In [25]:
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x, x) 

In [26]:
g = tape.gradient(y, x) 
print(g.numpy()) 

-2.0


In [28]:
import tensorflow as tf 
# Generate grayscale image 
gray = tf.random.uniform([2, 2], maxval=255, dtype='int32') 
gray

<tf.Tensor: id=105, shape=(2, 2), dtype=int32, numpy=
array([[150,  95],
       [ 21,  95]])>

In [29]:
# Reshape grayscale image
gray = tf.reshape(gray, [2*2, 1]) 
gray

<tf.Tensor: id=107, shape=(4, 1), dtype=int32, numpy=
array([[150],
       [ 95],
       [ 21],
       [ 95]])>